version: '3.4'

services:
  article.api:
    image: eerp/article.api
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5102:80"
    build:
      context: .
      dockerfile: src/services/Article/Article.Api/Dockerfile
  websupervisor:
    image: eerp/websupervisor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports :
      - "5100:80"
    build:
      context: .
      dockerfile: src/web/WebSupervisor/Dockerfile