version: '3.4'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
      
  article.api:
    image: eerp/article.api
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5102:80"
    build:
      context: .
      dockerfile: src/services/Article/Article.Api/Dockerfile
    depends_on:
      - rabbitmq
  websupervisor:
    image: eerp/websupervisor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports :
      - "5100:80"
    build:
      context: .
      dockerfile: src/web/WebSupervisor/Dockerfile
volumes:
  rabbitmq_data:
    driver: local